### Necessário para pegar o token 
# @name loginAutenticado
POST http://localhost:40000/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin", 
    "password": "admin"
}

### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}

### TESTE DE INSERÇÃO DE GÊNERO
POST http://localhost:40000/insertGenero HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nome": "Ficção Científica 2"
}

### TESTE DE BUSCAR TODOS OS GÊNEROS
GET http://localhost:40000/getAllGenero HTTP/1.1
Authorization: Bearer {{accessToken}}

{
}

### TESTE DE BUSCAR GÊNERO POR ID
POST http://localhost:40000/getGeneroById HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": 7
}

### TESTE DE ATUALIZAÇÃO DE GÊNERO
POST http://localhost:40000/updateGenero HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": 7,
    "nome": "Ficção Científica Atualizada"
}

### TESTE DE SOFT DELETE DE GÊNERO
POST http://localhost:40000/deleteGenero HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": 7
}