### Necessário para pegar o token 
# @name loginAutenticado
POST http://localhost:40000/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin", 
    "password": "admin"
}

### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}

### TESTE DE INSERÇÃO DE FUNCIONÁRIO
POST http://localhost:40000/insertFuncionario HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nome": "Thiago Souza",
    "username": "thiagos",
    "password": "senha123",
    "email": "thiago.souza@example.com"
}


### TESTE DE BUSCAR TODOS OS FUNCIONÁRIOS
GET http://localhost:40000/getAllFuncionario HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
}

### TESTE DE BUSCAR FUNCIONÁRIO POR ID
POST http://localhost:40000/getFuncionarioById HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": 8
}

### TESTE DE ATUALIZAÇÃO DE FUNCIONÁRIO
POST http://localhost:40000/updateFuncionario HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": 8,
    "nome": "Thiago Souza",
    "username": "thiagos",
    "password": "123senha",
    "email": "thiago.souza@example.com"
}
### TESTE DE SOFT DELETE DE FUNCIONÁRIO
POST http://localhost:40000/deleteFuncionario HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": 3
}